version: '2'
services:

  web:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
       - "8000:8000"
    depends_on:
       - postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
