version: '2'
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web

  web:
    restart: always
    build: ./web/
    volumes:
      - .:/usr/src/app
    depends_on:
       - postgres
    env_file: ./web/.env

  postgres:
    restart: always
    image: postgres:latest
    env_file: ./web/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
