version: '2'
services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
       - postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
